spring.application.name=MovieService

server.port=${PORT:8080}

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

logging.level.org.springframework.security=DEBUG